language: node_js
node_js:
node_js:
  - 0.8
before_install:
  - npm -g update npm
notifications:
  email:
    recipients:
      - evan.cordell@localmed.com
    on_success: change
    on_failure: always
after_success:
  - ./scripts/coveralls
