// Generated by CoffeeScript 1.6.3
var SslSupport, fs, https, winston;

https = require('https');

fs = require('fs');

winston = require('winston');

SslSupport = (function() {
  function SslSupport(app, options) {
    var serverOptions;
    serverOptions = {
      key: fs.readFileSync(options.key),
      cert: fs.readFileSync(options.cert)
    };
    https.createServer(serverOptions, app).listen(options.port, options.host);
    winston.info('Listening on ' + options.host + ':' + options.port + ' (HTTPS)');
  }

  return SslSupport;

})();

module.exports = SslSupport;
